[package]
name = "riptide"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.2"
ndarray = "0.16.1"
video-rs = { version = "0.10.3", features = [ "ndarray" ] }
thiserror = "2.0.9"
smallvec = "1.13.2"
clap = { version = "4.5.23", features = [ "derive" ] }
indicatif = "0.17.9"
